### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by shuijinliuxi** [runner365/LiveVideoCoreSDK#11]
xcode 7.2.1

/Users/xxx/Downloads/LiveVideoCoreSDK-master/RtmpLivePushSDK/VideoCore/transforms/Apple/H264Encode.mm:186:51: NSNumber must be available to use Objective-C literals
/Users/xxx/Downloads/LiveVideoCoreSDK-master/RtmpLivePushSDK/VideoCore/transforms/Apple/H264Encode.mm:186:51: Illegal type '(anonymous enum at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVPixelBuffer.h:35:1)' used in a boxed expression

**Comment by runner365** [comment]
不支持虚拟机，只支持真机编译。
