### ISSUE TITLE
推流失败

### ISSUE THREAD

**Issue by XuDachuang** [runner365/LiveVideoCoreSDK#20]
直播一段时间会出现
ERROR: WriteN, RTMP send error 9 (42 bytes)
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
然后就停止推流了

**Comment by runner365** [comment]
这个是因为网络不通导致，经常遇到网友设置一个非常高的分辨率，但是速率有配置很低，网络又达不到要求，所以会导致网络断
