### ISSUE TITLE
怎么把RtmpLivePushSDK抽出来放到我自己的项目中去

### ISSUE THREAD

**Issue by iOSSinger** [runner365/LiveVideoCoreSDK#21]
我想自己做下修改并自己封装,但是RtmpLivePushSDK放到项目中会报错
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_VCSimpleSession", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

我的集成方法是把RtmpLivePushSDK工程放到我的工程中去

**Comment by runner365** [comment]
IOS基础问题，自己去搞
