### ISSUE TITLE
引用只成功过一次，之后全部都是错误引用

### ISSUE THREAD

**Issue by lennondong** [runner365/LiveVideoCoreSDK#22]
因为不想在自己的工程中有那么多的xcodeproj文件，所以只是把其他必要的文件引入工程，结果，各种出错，各种引用不对。真是无语了。

库主讲一下，这两个LiveVideoCoreSDK、RtmpLivePushSDK该如何加到工程里吧？给点建议吧。真心不想要那些xcodeproj格式文件。

**Comment by runner365** [comment]
ios工程基本功都问题，请自己学习
