### ISSUE TITLE
美颜效果变成鱼眼。

### ISSUE THREAD

**Issue by zhouzizi** [runner365/LiveVideoCoreSDK#24]
rt，我初始化的参数和Demo一样。
但是设置美颜效果，图像变成鱼眼效果了！

**Comment by runner365** [comment]
那肯定是加载了鱼眼的滤镜，参数穿错了，或者对应错了，你自己定位一下

**Comment by zhouzizi** [comment]
没有办法定位啊。我设置的LiveVideoCoreSDK.sharedinstance().setFilter(LIVE_FILTER_TYPE.BEAUTY)。你的代码我一点没动。

**Comment by runner365** [comment]
我的demo工作是正常的，你对比一下就能定位出你自己的问题。

**Comment by zhouzizi** [comment]
是不是在swift的项目上会这样的啊？我的项目是swift的

**Comment by zhouzizi** [comment]
我把LiveVideoCoreSDK.m里的setFilter方

法直接改成beauty的，还是不行？！
- (void)setFilter:(LIVE_FILTER_TYPE) type{
    [_livesession setFilter:VCFilterBeauty];
}

**Comment by zhouzizi** [comment]
其他的滤镜我都试过了。都可以。就美颜的不行
