### ISSUE TITLE
能否修改码流LIVE_BITRATE这个参数？

### ISSUE THREAD

**Issue by wumengworld** [runner365/LiveVideoCoreSDK#26]
感谢作者的代码贡献。请问修改码流的数据后不能正常推流了 请问这个数据是否不能修？如果想降低推流的码流该怎么做

**Comment by runner365** [comment]
已经提供了，多种码流和帧率适配选择：
typedef NS_ENUM(NSUInteger, LIVE_BITRATE) {
    LIVE_BITRATE_1Mbps=1500000,
    LIVE_BITRATE_800Kbps=800000,
    LIVE_BITRATE_600Kbps=600000,
    LIVE_BITRATE_300Kbps=300000
};

typedef NS_ENUM(NSUInteger, LIVE_FRAMERATE) {
    LIVE_FRAMERATE_30=30,
    LIVE_FRAMERATE_25=25,
    LIVE_FRAMERATE_20=20,
    LIVE_FRAMERATE_15=15
};
