### ISSUE TITLE
ERROR: WriteN, RTMP send error 35 (129 bytes

### ISSUE THREAD

**Issue by haoXu1990** [runner365/LiveVideoCoreSDK#27]
LOG 和界面上来看RTMP 服务器已经连接成功了，
但是在传输数据的时候报如下错误，请问是我服务器配置错误了吗？
ERROR: WriteN, RTMP send error 35 (129 bytes)
ERROR: WriteN, RTMP send error 35 (39 bytes)
ERROR: RTMP_Connect1, handshake failed.
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
ERROR: RTMP connection poll error, ret=0, Operation now in progress

**Comment by runner365** [comment]
这个是发送数据多次失败后，socket connect断开了。

**Comment by haoXu1990** [comment]
敢写您的回答:
我通过如下方式解决了上面的问题
/usr/local/Cellar/nginx-full/1.10.0/bin/nginx -s reload

/usr/local/Cellar/nginx-full/1.10.0/bin/nginx -c /usr/local/etc/nginx/nginx.conf

但是在推流的时候，如果切换了摄像头的话，还是会报上面那种错误，不确定是哪里的问题。服务器配置方面不太懂，只有自己补补了。
再次谢谢您

**Comment by ICantCoding** [comment]
/usr/local/Cellar/nginx-full/1.10.0/bin/nginx -s reload
/usr/local/Cellar/nginx-full/1.10.0/bin/nginx -c /usr/local/etc/nginx/nginx.conf
这两句是什么意思？

**Comment by phantomgz** [comment]
重启nginx 治标不治本, 还是会出现同样的情况.
网络状况不太好的情况下, 时间稍长这种状况会一直重复出现, 无法恢复正常上行, 
在nginx看log, 会发现这个流不断的断开, 然后重连

**Comment by runner365** [comment]
网络不太好，就是上行带宽不够，肯定会出现断开和重连的情况。
这个是因为，本来网络上行质量就不够，发不出去，自然会断开。
你觉得软件应该怎么处理？
