### ISSUE TITLE
这个是videocore实现的

### ISSUE THREAD

**Issue by singer1026** [runner365/LiveVideoCoreSDK#3]
请问有用ffmpeg实现的没编码推流的吗。
我这两天也在看VideoCore这个库 发现挺厉害的，不过我没仔细看他的有滤镜这东西。
我自己用CoreImage加的滤镜，折腾死了，效果还不是很好。

这里也还有个库跟你的方式差不多
https://github.com/yuyedaidao/pili-ios-camera-recorder

**Comment by runner365** [comment]
谢谢推荐，我用过ffmpeg+x264进行编码，然后推流，因为ffmpeg是软编码，容易发烫，手机无法做长时间的拍摄直播，所以后来放弃了这个方案。
编码效率的话，我个人还是倾向于手机GPU编码。

**Comment by singer1026** [comment]
我根据你的这个sdk和你的美颜滤镜  我把ijkplayer加上 弄了个简单的视频聊天Demo

**Comment by youhui** [comment]
@singer1026  求共享
