### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhouzizi** [runner365/LiveVideoCoreSDK#30]
在推流过程中

ERROR: WriteN, RTMP send error 35 (21 bytes)
ERROR: WriteN, RTMP send error 35 (110 bytes)
ERROR: WriteN, RTMP send error 9 (42 bytes)

**Comment by runner365** [comment]
报文发送失败，上传带宽是否足够？

**Comment by zhouzizi** [comment]
一直打印这个log
ERROR: RTMP_ReadPacket, failed to read RTMP packet header

**Comment by zhouzizi** [comment]
WIFI正常的情况测试的。
