### ISSUE TITLE
新建的滤镜,设置提示Null texture!

### ISSUE THREAD

**Issue by coffeeGF** [runner365/LiveVideoCoreSDK#31]
新建的滤镜是和demo中的美颜 改了level和命名的，但是setFilter之后，图3的filter为NULL，并且log出Null texture!
![2016-06-14 10 59 20](https://cloud.githubusercontent.com/assets/9649080/16030063/939d3582-3220-11e6-9110-82344eda22ef.png)
![2016-06-14 11 01 40](https://cloud.githubusercontent.com/assets/9649080/16030065/947d8b78-3220-11e6-810b-a13113d9eca5.png)
![2016-06-14 11 02 11](https://cloud.githubusercontent.com/assets/9649080/16030064/9477eccc-3220-11e6-9d76-a9499bbf6a79.png)

求正确设置滤镜的思路

**Comment by coffeeGF** [comment]
Xcode->Clean->Run 就可以了

**Comment by runner365** [comment]
是的，xcode好像有这个bug
