### ISSUE TITLE
LiveVideoCoreSDK exit syn Bug

### ISSUE THREAD

**Issue by com314159** [runner365/LiveVideoCoreSDK#33]
I find two Bug:

1. when OnExitClicked disconnect the RTMP session,  if RTMP send queue is over 100 (Bad network), it will cause too mush time to exit, and maybe crash. 

2. When two LiveShowViewController is opened at the same time, it will crash. some people may click too fast , will open two view controller.

to fix the first bug, my method is

in VCSimpleSession add method:

    - (void) endRtmpSessionAsyn:(void (^)())done {
    
    NSLog(@"退出 endRtmpSessionAsyn %p",self);
       //这里必须使用强引用, 等执行完才能执行dealloc, 否则队列里面还有任务要执行, self已经销毁会崩溃
     // only when _graphManagementQueue is empty can self be dealloc, or it will crash 
    dispatch_async(_graphManagementQueue, ^{
        [self endRtmpSession];
        
        if (done) {
            done();
        }
        NSLog(@"退出成功 %p",self);
    });    }

in LiveVideoCoreSDK  add method,  and call this method when OnExitClicked

     - (void) disconnectAsynAndRelease {
        [_livesession endRtmpSessionAsyn:^{
        _livesession = nil;
       }];
    }

**Comment by runner365** [comment]
thanks for your issue, but is it only for this "some people may click too fast , will open two view controller".

**Comment by com314159** [comment]
NO, there are two bug.  the first one is that when exit the Viewcontroller and disconnect livesession, it will speed too much time on main thread.

And if exit on the background thread, LiveVideoCoreSDK can't be a single instance. if use single instance,  some circumstance will crash. like: when a liveVideoCoreSDK is exiting on background thread, a liveVideoCoreSDK is start on main thread at the same time, it will conflict and crash.

**Comment by runner365** [comment]
thanks
