### ISSUE TITLE
滤镜修改

### ISSUE THREAD

**Issue by coffeeGF** [runner365/LiveVideoCoreSDK#34]
1.beautyFilter中的 vec3 lvse = vec3(1.0)-(vec3(1.0)-smoothColor)*(vec3(1.0)-centralColor);是为了变白吗？
2.我想将滤镜的整体颜色变粉一点，如果按1中的修改方法，该如何修改RGBA中的R。
~~please help

**Comment by coffeeGF** [comment]
muhaha. 
这样做应该没有问题吧
 gl_FragColor = vec4(clamp(pow(centralColor.r+0.4, params.g),0.0,1.0), centralColor.g, centralColor.b, 1.0);

**Comment by runner365** [comment]
这样整个画面的颜色都会变

**Comment by coffeeGF** [comment]
gl_FragColor = vec4(clamp(centralColor.r*1.8,0.0,1.0), clamp(centralColor.g*1.2,0.0,1.0), centralColor.b, 1.0);
是的。之前的pow函数不对；现在的效果也是将整个画面的颜色都改变了。请问有什么好的建议吗？

**Comment by runner365** [comment]
算法不对，高斯算法解决不了这个东西。
需要自己研究了。
