### ISSUE TITLE
推流中断！

### ISSUE THREAD

**Issue by zhouzizi** [runner365/LiveVideoCoreSDK#35]
在正常推流的过程中，网络是稳定的WIFI
```
ERROR: WriteN, RTMP send error 32 (140 bytes)
ERROR: WriteN, RTMP send error 32 (110 bytes)
ERROR: WriteN, RTMP send error 9 (42 bytes)
```
然后就是一直Log
```
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
```
然后connectionStatusChanged 又没有监听到状态改变
等了超级久还是不行。
如果我自己写一个定时监听这个sessionState状态，这个时候的状态是PreviewStarted,
这时候如果断流后再重新推流还是不行，一直打印这个Log！

**Comment by runner365** [comment]
你推流的带宽是否要求过高，手机推流最好不要超过1.5m。
