### ISSUE TITLE
Definition of class NSNumber must be available to use Objective-C numeric literals

### ISSUE THREAD

**Issue by iHuangjian** [runner365/LiveVideoCoreSDK#36]
请问这是什么错误？

LiveVideoCoreSDK-master/RtmpLivePushSDK/VideoCore/transforms/Apple/H264Encode.mm:187:51: Definition of class NSNumber must be available to use Objective-C numeric literals

**Comment by adteven** [comment]
我也越到这个问题了，你是怎么解决的

**Comment by runner365** [comment]
哪块代码？是否你没有用真机调试？

**Comment by adteven** [comment]
编译出现出，直接build

**Comment by adteven** [comment]
NSDictionary* pixelBufferOptions = @{ (NSString*) kCVPixelBufferPixelFormatTypeKey : //@(kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange),
                                                  @(kCVPixelFormatType_32BGRA),
                                                  (NSString*) kCVPixelBufferWidthKey : @(m_frameW),
                                                  (NSString*) kCVPixelBufferHeightKey : @(m_frameH),
                                                  (NSString*) kCVPixelBufferOpenGLESCompatibilityKey : @YES,
                                                  (NSString*) kCVPixelBufferIOSurfacePropertiesKey : @{}};


这里提示kCVPixelFormatType_32BGRA这个

**Comment by phantomgz** [comment]
I have meet same issue,  Like runner365 said, If plug in  with a real machine and select build with it, This issue has gone.

**Comment by runner365** [comment]
请真机调试。

**Comment by xiongjie1207** [comment]
终于解决了
