### ISSUE TITLE
集成

### ISSUE THREAD

**Issue by SmallwolfiOS** [runner365/LiveVideoCoreSDK#41]
请问如何集成到自己的工程中呢

**Comment by runner365** [comment]
ios工程基本功，自己去研究。

**Comment by erduoniba** [comment]
请问如何集成到自己的工程中呢?

https://github.com/erduoniba/HDLiveVideoCoreDemo/blob/master/%E7%9B%B4%E6%92%AD%E6%8A%80%E6%9C%AF%E6%B1%87%E6%80%BB.md
