### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by XuDachuang** [runner365/LiveVideoCoreSDK#42]
请问你的这个项目支持ipv6吗？

**Comment by kexuebin** [comment]
请问你的这个项目支持ipv6吗？

**Comment by XuDachuang** [comment]
我的底层是支持的。但是我不知道你的这个上流rtmp会不会有问题？在ipv6的环境的可不可以上流

**Comment by runner365** [comment]
恩，因为网络库不支持ipv6网络，所以导致崩溃和审核不过。你自己去编译一个支持ipv6的librtmp库，就可以审核过了。
我们自己的app已经审核过了。
