### ISSUE TITLE
提交了两次itunes，都提示说崩溃，请问是怎么回事，原itunes回复如下：

### ISSUE THREAD

**Issue by kexuebin** [runner365/LiveVideoCoreSDK#43]
Performance - 2.1

Your app crashes on iPhone running iOS 9.3.2 when we:

1. Launched the application
2. Filled in all login credentials
3. Tapped on 开始直播 section

This occurred when your app was used:
- On Wi-Fi

We have attached detailed crash logs to help troubleshoot this issue.

Next Steps

Please revise your app and test it on a device to ensure that it runs as expected.

Apps are reviewed on an IPv6 network. Please ensure that your app supports IPv6 networks, as IPv6 compatibility is required.

For additional information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and About Networking.

Resources

For information on how to symbolicate and read a crash log, please see Tech Note TN2151 Understanding and Analyzing iPhone OS Application Crash Reports.

If you have difficulty reproducing this issue, please try testing the workflow described in Testing Workflow with Xcode's Archive feature.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

**Comment by runner365** [comment]
恩，因为网络库不支持ipv6网络，所以导致崩溃和审核不过。你自己去编译一个支持ipv6的librtmp库，就可以审核过了。
我们自己的app已经审核过了。

**Comment by kexuebin** [comment]
麻烦作者发一个你们编译通过的IPV6好吗，研究了两天实在没弄出来，谢谢了。
511984450@qq.com
