### ISSUE TITLE
推流崩溃

### ISSUE THREAD

**Issue by congni** [runner365/LiveVideoCoreSDK#44]
![image](https://cloud.githubusercontent.com/assets/7497123/16514667/e36ee6f0-3f9f-11e6-8ced-c49e4d5243f9.png)

**Comment by congni** [comment]
![image](https://cloud.githubusercontent.com/assets/7497123/16514779/afc763da-3fa0-11e6-9359-67a5793c7c54.png)

**Comment by congni** [comment]
![image](https://cloud.githubusercontent.com/assets/7497123/16537931/de0803ea-4044-11e6-9a39-c174470f66e2.png)

**Comment by runner365** [comment]
怎么复现出来的？有什么复现条件吗？
第一张图是刚打开摄像头就崩溃了；
第二张图是退出拍摄的时候，出现崩溃；
你用的是最新的代码吗？

**Comment by ICantCoding** [comment]
我也出现ERROR: WriteN, RTMP send error 35 (102 bytes),但是没有应用没有崩溃！
