### ISSUE TITLE
推的流多了一个字幕流  请问怎么去掉？

### ISSUE THREAD

**Issue by RonbeKing** [runner365/LiveVideoCoreSDK#49]
正常推流 流0是视频流，流1是音频流，但是这个多出了流2 字幕流，导致播放器报2096错误，请问怎么才能去掉流2？

**Comment by runner365** [comment]
没听说过，还有个字幕流，而且音频与视频流是两个流，rtmp的音频、视频流是在一块的。
不明白你的问题。
