### ISSUE TITLE
请问librtmp库是否做过修改？

### ISSUE THREAD

**Issue by liuf1986** [runner365/LiveVideoCoreSDK#53]
我尝试使用http://rtmpdump.mplayerhq.hu/download/下rtmpdump-2.3.tgz源码引入工程，但并没有connect成功，请问你提供的librtmp是否做了修改，修改了哪些地方呢？

**Comment by runner365** [comment]
做过修改:
1, 加入了Ipv6的支持；
2，connect采用异步方式，防止被系统锁死；
3，connect用no_sign的方式，防止异常崩溃；
