### ISSUE TITLE
请问下推流上去的视频没有metadata吗

### ISSUE THREAD

**Issue by Zeaa** [runner365/LiveVideoCoreSDK#54]
使用LiveVideoCore，推到网宿的rtmp服务器上，在网页端播放的时候拿不到metadata，想知道是推流端的问题还是那边服务器的问题，谢谢

**Comment by runner365** [comment]
metadata你需要哪些数据，可以自己推一下啊

**Comment by Zeaa** [comment]
问题是不知道怎么推，c++不熟啊，大神，可否指点一二呢。。

**Comment by Zeaa** [comment]
@runner365 问题是不知道怎么推，c++不熟啊，大神，可否指点一二呢。。

**Comment by runner365** [comment]
开源的意思就是，请自己看源码。
