### ISSUE TITLE
Can't build with Xcode 7.3.1

### ISSUE THREAD

**Issue by lukegao** [runner365/LiveVideoCoreSDK#56]
Xcode complained about these:
> Undefined symbols for architecture x86_64:
  "_RTMPPacket_Alloc", referenced from:
      LibRtmpSession::SendAudioSpecificConfig(int, int, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendPacket(unsigned int, unsigned char*, unsigned int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendVideoSpsPps(unsigned char*, int, unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendAACData(unsigned char*, int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMPPacket_Free", referenced from:
      LibRtmpSession::SendPacket(unsigned int, unsigned char*, unsigned int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMPPacket_Reset", referenced from:
      LibRtmpSession::SendAudioSpecificConfig(int, int, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendPacket(unsigned int, unsigned char*, unsigned int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendVideoSpsPps(unsigned char*, int, unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendAACData(unsigned char*, int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Alloc", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Close", referenced from:
      LibRtmpSession::DisConnect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_ConnectEx", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_ConnectStream", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_EnableWrite", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Free", referenced from:
      LibRtmpSession::DisConnect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_GetTime", referenced from:
      LibRtmpSession::SendAudioData(unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendVideoData(unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Init", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_IsConnected", referenced from:
      LibRtmpSession::IsConnected() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_SendPacket", referenced from:
      LibRtmpSession::RtmpPacketSend(RTMPPacket*) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_SetupURL", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by runner365** [comment]
IT must be compile on device, not for x84

**Comment by lijihua** [comment]
ld: library not found for -lLiveVideoCoreSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation),这个找不到,linked frameworks and lobraries添加的时候也没有供选择的项.
