### ISSUE TITLE
使用4G或者Wifi推流的时候, 会出现一段段视频网上传, 这是啥原因?

### ISSUE THREAD

**Issue by CainRun** [runner365/LiveVideoCoreSDK#57]
使用4G或者Wifi推流的时候, 会出现一段段视频网上传, 这是啥原因?

**Comment by runner365** [comment]
你上传的带宽是多少，使用的分辨率，设置码率都是多少？

**Comment by CainRun** [comment]
4g网络, 1280*720, 800000bps, 而且sessionState偶尔还会抽风, 状态显示不对

**Comment by runner365** [comment]
720p需要的低保码率是1.5mpbs， 如果低于这个，就会时常的断流。
通常手机直播推荐的最高码率和分辨率是，540*960，800kbps.
发现很多人都没有正确的使用分辨率和码率。
