### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by XuDachuang** [runner365/LiveVideoCoreSDK#58]
大牛，如果我想接入别人的滤镜和ar效果，该怎么做。能不能出一个接口出来，把图片流输出来给我们进行处理？

**Comment by runner365** [comment]
这个可以直接做，在h264encode前，数据就是RGBA，这个是可以直接写图片文件的。
你可以自己搞一下。

**Comment by XuDachuang** [comment]
可以稍微具体点吗，我是菜鸟，c++的都不懂。我希望的是最好能确定什么方法，怎么把它那个流导出来处理下一再去上流

**Comment by runner365** [comment]
多滤镜的拍摄，最后结合推流的案例(GPUImage多滤镜采集，自己编码和推流)，见我的另外一个开源：
https://github.com/runner365/GPUImageRtmpPush
