### ISSUE TITLE
'type_half.inl' file not found

### ISSUE THREAD

**Issue by futomtom** [runner365/LiveVideoCoreSDK#6]
請問 pod install
Installing glm (0.9.4.6)

compiled error
 LiveVideoCoreSDK/Pods/Headers/Private/glm/core/type_half.hpp:116:10: 'type_half.inl' file not found

請問您有遇到這編譯錯誤嗎？ 或是用的是  glm (0.9.4.6)嗎？

**Comment by yscGit** [comment]
gem install cocoapods --pre

**Comment by runner365** [comment]
Pods/Headers/Public/glm/core
可以考虑添加上面这个目录的header文件路径

**Comment by 709213219** [comment]
您好，请问您这个问题解决了吗？ 怎么解决的？

**Comment by futomtom** [comment]
我后来去 http://code4app.com/ 那下一个LiveVideoCoreSDK的zip档 那是可以编译执行的. 应该是cocopad 第三方lib 不同版本的问题

**Comment by 709213219** [comment]
谢谢你。
我研究了一下错误报告，发现是因为Pods/Headers/Private/glm/core文件夹中缺少.inl文件(public/glm/core中是有.inl文件)。后面我的解决方法是：将Private文件夹拖放到桌面，编译可以通过，然后可以再把Private文件夹拖回到Headers文件夹中，编译还是可以通过。
