### ISSUE TITLE
怎么取得推流的实时码率、延迟时长等信息

### ISSUE THREAD

**Issue by zhiyuanily** [runner365/LiveVideoCoreSDK#60]

**Comment by zhiyuanily** [comment]
或者说怎么动态修改码率

**Comment by runner365** [comment]
码率在编码前必需设定好，编码参数不能动态设定，但是可以调整rtmp上传速率，在不得已的情况下，丢弃P帧。
关键还是在直播过程中，要保证上传带宽。
再则，请明确上传的分辨率和码率是否匹配：
分辨率,速率配对关系:
1, 720x1280:至少1.5mbps;
2, 540x960: 至少800kbps;
3, 360x640: 至少:600kbps;

**Comment by zhiyuanily** [comment]
ok，3q
