### ISSUE TITLE
err

### ISSUE THREAD

**Issue by myjawdrops** [runner365/LiveVideoCoreSDK#64]
运行工程会在 H264Encode.m 中的一个枚举量上 @(kCVPixelFormatType_32BGRA), 报两个错误，一个是 Definition of class NSNumber must be available to use Objective-C numeric literals,  一个是Illegal type (anonymous enum at .../.../...)  
求解释或解决

**Comment by xiongjie1207** [comment]
遇到同样的问题，最后怎么解决的？

**Comment by runner365** [comment]
因为是硬编码，所以必须要手机真机调试
