### ISSUE TITLE
RTMP_Connect1, handshake failed.

### ISSUE THREAD

**Issue by john28463719** [runner365/LiveVideoCoreSDK#66]
2016-11-29 21:26:19.965 LiveVideoCoreDemo[9526:3546034] rtmp live state: 1
INFO:  connect successd.
ERROR: WriteN, RTMP send error 57 (1537 bytes)
ERROR: RTMP_Connect1, handshake failed.
ClientState: 2

請問這是我服務器沒配置好嗎？
socket沒問題,也可以傳影片,只有直播不行(內網直播可以)

**Comment by runner365** [comment]
这个提示是连接不上，应该是服务器没有配置好，你看看你的服务器用obs可以推流成功吗？

**Comment by john28463719** [comment]
rtmp {
    server {
            listen 1935;
            chunk_size 4096;

            application live {
                    live on;
                    record off;
                    exec ffmpeg -i rtmp://localhost/live/$name -threads 1 -c:v libx264 -profile:v baseline -b:v 350K -s 640x360 -f flv -c:a aac -ac 1 -strict -2 -b:a 56k rtmp://localhost/live360p/$name;
            }
            application live360p {
                    live on;
                    record off;
        }
    }
}           
我服務器這樣設置 
剛實測過obs是可以推流成功的
我昨天在試了一下有成功過一兩次,但多數是失敗

**Comment by john28463719** [comment]
sorry 我重新下載一次sdk就好了
可能有不小心改到code
