### ISSUE TITLE
导入入项目运行不了 ，求解决方法

### ISSUE THREAD

**Issue by xiaoGoO** [runner365/LiveVideoCoreSDK#67]
Undefined symbols for architecture x86_64:
  "_RTMPPacket_Alloc", referenced from:
      LibRtmpSession::SendAudioSpecificConfig(int, int, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendPacket(unsigned int, unsigned char*, unsigned int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendVideoSpsPps(unsigned char*, int, unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendAACData(unsigned char*, int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMPPacket_Free", referenced from:
      LibRtmpSession::SendPacket(unsigned int, unsigned char*, unsigned int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMPPacket_Reset", referenced from:
      LibRtmpSession::SendAudioSpecificConfig(int, int, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendPacket(unsigned int, unsigned char*, unsigned int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendVideoSpsPps(unsigned char*, int, unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendAACData(unsigned char*, int, unsigned int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Alloc", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Close", referenced from:
      LibRtmpSession::DisConnect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_ConnectEx", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_ConnectStream", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_EnableWrite", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Free", referenced from:
      LibRtmpSession::DisConnect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_GetTime", referenced from:
      LibRtmpSession::SendAudioData(unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
      LibRtmpSession::SendVideoData(unsigned char*, int) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_Init", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_IsConnected", referenced from:
      LibRtmpSession::IsConnected() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_SendPacket", referenced from:
      LibRtmpSession::RtmpPacketSend(RTMPPacket*) in libLiveVideoCoreSDK.a(LibRtmpSession.o)
  "_RTMP_SetupURL", referenced from:
      LibRtmpSession::Connect() in libLiveVideoCoreSDK.a(LibRtmpSession.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by runner365** [comment]
1,当前只支持真机调试；
2,项目合入的基本功，可以自己解决；

**Comment by xiaoGoO** [comment]
恩恩，谢谢已经清楚问题所在
