### ISSUE TITLE
开启直播就挂

### ISSUE THREAD

**Issue by renmoqiqi** [runner365/LiveVideoCoreSDK#7]
LiveVideoCoreDemo[2456:1021029] rtmp live state: 1
ClientState: 1
2016-03-07 10:23:50.730 LiveVideoCoreDemo[2456:1021028] rtmp live state: 2
ClientState: 2
ClientState: 3
ClientState: 4
ClientState: 5
ClientState: 6
received server window size: 2500000
received peer bandwidth limit: 2500000 type: 2
received ping, sending pong.
Received invoke
pktId: 1
received invoke _result
tracked command: connect
ClientState: 7
received unknown packet type: 0x15
Received invoke
pktId: 4
received invoke _result
tracked command: createStream
ClientState: 8
received ping, sending pong.
Received invoke
pktId: 0
received invoke onStatus

![image](https://cloud.githubusercontent.com/assets/8848376/13559451/47a6ab32-e44f-11e5-9c7e-2ceeeecd1839.png)

**Comment by yanwt** [comment]
我也遇到同样的问题，rtmp地址后面带参数吗？

**Comment by runner365** [comment]
rtmp地址后面是带参数的。
问题主要出在：当前SDK支持的RTMP服务器类型有限，README.MD里面说明了。
本客户端支持Wowza, nginx-rtmp和Edgecast三种类型的RTMP服务器。不支持crtmpserver, red5和python rtmp server。
如果你有nginx-rtmp服务器，你可以测试，rtmp地址带参数，没有问题的。

**Comment by yanwt** [comment]
这个问题应该已经修复了，支持red5服务器了
